services:
  app:
    build:
      target: development
    volumes:
      - .:/var/www/html
    user: "${PUID:-1000}:${PGID:-1000}"
    environment:
      - APP_DEBUG=true

  web:
    volumes:
      - .:/var/www/html

  node:
    build:
      context: ./docker/node
    container_name: ${APP_NAME:-portfolio}_node
    volumes:
      - .:/var/www/html
    command: npm run dev
    tty: true
    ports:
      - "${VITE_PORT:-5173}:5173"
    networks:
      - portfolio_network
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
