version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile.dev
    volumes:
      - .:/var/www/html
    user: "${PUID:-1000}:${PGID:-1000}"
    # command: ["php", "artisan", "octane:start", "--server=frankenphp", "--host=0.0.0.0", "--port=8000", "--watch"]
    environment:
      - APP_DEBUG=true
    command: ["php", "artisan", "octane:start", "--server=frankenphp", "--host=0.0.0.0", "--port=8000"]

  web:
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html

  node:
    build:
      context: ./docker/node
    container_name: ${APP_NAME:-portfolio}_node
    volumes:
      - .:/var/www/html
    command: npm run dev
    tty: true
    ports:
      - "${VITE_PORT:-5173}:5173"
    networks:
      - portfolio_network
    security_opt:
      - no-new-privileges:true
